<?php

namespace AppBundle\Repository;

/**
 * EquipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipRepository extends \Doctrine\ORM\EntityRepository
{
}
