<?php

namespace AppBundle\Repository;

/**
 * LigaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigaRepository extends \Doctrine\ORM\EntityRepository
{
}
