<?php

namespace AppBundle\Repository;

/**
 * PartitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartitRepository extends \Doctrine\ORM\EntityRepository
{
}
